name: Python package

on:
  push:
    branches: [ "main" ]

jobs:

  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Version Tags
      id: versions
      run: |
        echo "BACKEND_VERSION=$(echo "$(<index/api/routes.py)" | grep -oP "(?<=version=\")[^\"]+")" >> "$GITHUB_OUTPUT"
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & push backend
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/scai-bio/backend:latest
          ghcr.io/scai-bio/backend:${{ steps.versions.outputs.BACKEND_VERSION }}
